/**
 * ثوابت التطبيق
 */

export const APP_CONFIG = {
  APP_NAME: 'تطبيق القرآن التعليمي',
  APP_VERSION: '1.0.0',
  DEFAULT_LANGUAGE: 'ar',
  DEFAULT_DIRECTION: 'rtl',
  DEFAULT_THEME: 'light',
  DEFAULT_FONT_SIZE: 18
};

export const RECITERS = [
  { id: 'ar.alafasy', name: 'مشاري العفاسي' },
  { id: 'ar.abdulbasitmurattal', name: 'عبد الباسط عبد الصمد (مرتل)' },
  { id: 'ar.abdullahbasfar', name: 'عبد الله بصفر' },
  { id: 'ar.abdurrahmaansudais', name: 'عبد الرحمن السديس' },
  { id: 'ar.hanirifai', name: 'هاني الرفاعي' },
  { id: 'ar.husary', name: 'محمود خليل الحصري' },
  { id: 'ar.mahermuaiqly', name: 'ماهر المعيقلي' },
  { id: 'ar.minshawi', name: 'محمد صديق المنشاوي' },
  { id: 'ar.muhammadayyoub', name: 'محمد أيوب' },
  { id: 'ar.muhammadjibreel', name: 'محمد جبريل' }
];

export const LANGUAGES = [
  { id: 'ar', name: 'العربية', direction: 'rtl' },
  { id: 'en', name: 'English', direction: 'ltr' },
  { id: 'ur', name: 'اردو', direction: 'rtl' },
  { id: 'fr', name: 'Français', direction: 'ltr' },
  { id: 'id', name: 'Bahasa Indonesia', direction: 'ltr' },
  { id: 'tr', name: 'Türkçe', direction: 'ltr' }
];

export const HADITH_BOOKS = [
  { id: 'bukhari', name: 'صحيح البخاري', chapters: 97 },
  { id: 'muslim', name: 'صحيح مسلم', chapters: 56 },
  { id: 'abudawud', name: 'سنن أبي داود', chapters: 43 },
  { id: 'tirmidhi', name: 'جامع الترمذي', chapters: 50 },
  { id: 'nasai', name: 'سنن النسائي', chapters: 51 },
  { id: 'ibnmajah', name: 'سنن ابن ماجه', chapters: 37 },
  { id: 'malik', name: 'موطأ الإمام مالك', chapters: 61 },
  { id: 'ahmad', name: 'مسند أحمد', chapters: 38 }
];

export const TAFSIR_SOURCES = [
  { id: 'ar-tafsir-al-jalalayn', name: 'تفسير الجلالين', language: 'ar' },
  { id: 'ar-tafsir-ibn-kathir', name: 'تفسير ابن كثير', language: 'ar' },
  { id: 'ar-tafsir-al-qurtubi', name: 'تفسير القرطبي', language: 'ar' },
  { id: 'ar-tafsir-al-tabari', name: 'تفسير الطبري', language: 'ar' },
  { id: 'en-tafsir-ibn-kathir', name: 'Tafsir Ibn Kathir', language: 'en' }
];

// أسماء السور مع أرقامها وعدد آياتها ومواقعها (رقم الصفحة)
export const SURAH_NAMES = [
  { number: 1, name: 'الفاتحة', ayahs: 7, page: 1 },
  { number: 2, name: 'البقرة', ayahs: 286, page: 2 },
  { number: 3, name: 'آل عمران', ayahs: 200, page: 50 },
  { number: 4, name: 'النساء', ayahs: 176, page: 77 },
  { number: 5, name: 'المائدة', ayahs: 120, page: 106 },
  { number: 6, name: 'الأنعام', ayahs: 165, page: 128 },
  { number: 7, name: 'الأعراف', ayahs: 206, page: 151 },
  { number: 8, name: 'الأنفال', ayahs: 75, page: 177 },
  { number: 9, name: 'التوبة', ayahs: 129, page: 187 },
  { number: 10, name: 'يونس', ayahs: 109, page: 208 },
  { number: 11, name: 'هود', ayahs: 123, page: 221 },
  { number: 12, name: 'يوسف', ayahs: 111, page: 235 },
  { number: 13, name: 'الرعد', ayahs: 43, page: 249 },
  { number: 14, name: 'إبراهيم', ayahs: 52, page: 255 },
  { number: 15, name: 'الحجر', ayahs: 99, page: 262 },
  { number: 16, name: 'النحل', ayahs: 128, page: 267 },
  { number: 17, name: 'الإسراء', ayahs: 111, page: 282 },
  { number: 18, name: 'الكهف', ayahs: 110, page: 293 },
  { number: 19, name: 'مريم', ayahs: 98, page: 305 },
  { number: 20, name: 'طه', ayahs: 135, page: 312 },
  { number: 21, name: 'الأنبياء', ayahs: 112, page: 322 },
  { number: 22, name: 'الحج', ayahs: 78, page: 332 },
  { number: 23, name: 'المؤمنون', ayahs: 118, page: 342 },
  { number: 24, name: 'النور', ayahs: 64, page: 350 },
  { number: 25, name: 'الفرقان', ayahs: 77, page: 359 },
  { number: 26, name: 'الشعراء', ayahs: 227, page: 367 },
  { number: 27, name: 'النمل', ayahs: 93, page: 377 },
  { number: 28, name: 'القصص', ayahs: 88, page: 385 },
  { number: 29, name: 'العنكبوت', ayahs: 69, page: 396 },
  { number: 30, name: 'الروم', ayahs: 60, page: 404 },
  { number: 31, name: 'لقمان', ayahs: 34, page: 411 },
  { number: 32, name: 'السجدة', ayahs: 30, page: 415 },
  { number: 33, name: 'الأحزاب', ayahs: 73, page: 418 },
  { number: 34, name: 'سبأ', ayahs: 54, page: 428 },
  { number: 35, name: 'فاطر', ayahs: 45, page: 434 },
  { number: 36, name: 'يس', ayahs: 83, page: 440 },
  { number: 37, name: 'الصافات', ayahs: 182, page: 446 },
  { number: 38, name: 'ص', ayahs: 88, page: 453 },
  { number: 39, name: 'الزمر', ayahs: 75, page: 458 },
  { number: 40, name: 'غافر', ayahs: 85, page: 467 },
  { number: 41, name: 'فصلت', ayahs: 54, page: 477 },
  { number: 42, name: 'الشورى', ayahs: 53, page: 483 },
  { number: 43, name: 'الزخرف', ayahs: 89, page: 489 },
  { number: 44, name: 'الدخان', ayahs: 59, page: 496 },
  { number: 45, name: 'الجاثية', ayahs: 37, page: 499 },
  { number: 46, name: 'الأحقاف', ayahs: 35, page: 502 },
  { number: 47, name: 'محمد', ayahs: 38, page: 507 },
  { number: 48, name: 'الفتح', ayahs: 29, page: 511 },
  { number: 49, name: 'الحجرات', ayahs: 18, page: 515 },
  { number: 50, name: 'ق', ayahs: 45, page: 518 },
  { number: 51, name: 'الذاريات', ayahs: 60, page: 520 },
  { number: 52, name: 'الطور', ayahs: 49, page: 523 },
  { number: 53, name: 'النجم', ayahs: 62, page: 526 },
  { number: 54, name: 'القمر', ayahs: 55, page: 528 },
  { number: 55, name: 'الرحمن', ayahs: 78, page: 531 },
  { number: 56, name: 'الواقعة', ayahs: 96, page: 534 },
  { number: 57, name: 'الحديد', ayahs: 29, page: 537 },
  { number: 58, name: 'المجادلة', ayahs: 22, page: 542 },
  { number: 59, name: 'الحشر', ayahs: 24, page: 545 },
  { number: 60, name: 'الممتحنة', ayahs: 13, page: 549 },
  { number: 61, name: 'الصف', ayahs: 14, page: 551 },
  { number: 62, name: 'الجمعة', ayahs: 11, page: 553 },
  { number: 63, name: 'المنافقون', ayahs: 11, page: 554 },
  { number: 64, name: 'التغابن', ayahs: 18, page: 556 },
  { number: 65, name: 'الطلاق', ayahs: 12, page: 558 },
  { number: 66, name: 'التحريم', ayahs: 12, page: 560 },
  { number: 67, name: 'الملك', ayahs: 30, page: 562 },
  { number: 68, name: 'القلم', ayahs: 52, page: 564 },
  { number: 69, name: 'الحاقة', ayahs: 52, page: 566 },
  { number: 70, name: 'المعارج', ayahs: 44, page: 568 },
  { number: 71, name: 'نوح', ayahs: 28, page: 570 },
  { number: 72, name: 'الجن', ayahs: 28, page: 572 },
  { number: 73, name: 'المزمل', ayahs: 20, page: 574 },
  { number: 74, name: 'المدثر', ayahs: 56, page: 575 },
  { number: 75, name: 'القيامة', ayahs: 40, page: 577 },
  { number: 76, name: 'الإنسان', ayahs: 31, page: 578 },
  { number: 77, name: 'المرسلات', ayahs: 50, page: 580 },
  { number: 78, name: 'النبأ', ayahs: 40, page: 582 },
  { number: 79, name: 'النازعات', ayahs: 46, page: 583 },
  { number: 80, name: 'عبس', ayahs: 42, page: 585 },
  { number: 81, name: 'التكوير', ayahs: 29, page: 586 },
  { number: 82, name: 'الانفطار', ayahs: 19, page: 587 },
  { number: 83, name: 'المطففين', ayahs: 36, page: 587 },
  { number: 84, name: 'الانشقاق', ayahs: 25, page: 589 },
  { number: 85, name: 'البروج', ayahs: 22, page: 590 },
  { number: 86, name: 'الطارق', ayahs: 17, page: 591 },
  { number: 87, name: 'الأعلى', ayahs: 19, page: 591 },
  { number: 88, name: 'الغاشية', ayahs: 26, page: 592 },
  { number: 89, name: 'الفجر', ayahs: 30, page: 593 },
  { number: 90, name: 'البلد', ayahs: 20, page: 594 },
  { number: 91, name: 'الشمس', ayahs: 15, page: 595 },
  { number: 92, name: 'الليل', ayahs: 21, page: 595 },
  { number: 93, name: 'الضحى', ayahs: 11, page: 596 },
  { number: 94, name: 'الشرح', ayahs: 8, page: 596 },
  { number: 95, name: 'التين', ayahs: 8, page: 597 },
  { number: 96, name: 'العلق', ayahs: 19, page: 597 },
  { number: 97, name: 'القدر', ayahs: 5, page: 598 },
  { number: 98, name: 'البينة', ayahs: 8, page: 598 },
  { number: 99, name: 'الزلزلة', ayahs: 8, page: 599 },
  { number: 100, name: 'العاديات', ayahs: 11, page: 599 },
  { number: 101, name: 'القارعة', ayahs: 11, page: 600 },
  { number: 102, name: 'التكاثر', ayahs: 8, page: 600 },
  { number: 103, name: 'العصر', ayahs: 3, page: 601 },
  { number: 104, name: 'الهمزة', ayahs: 9, page: 601 },
  { number: 105, name: 'الفيل', ayahs: 5, page: 601 },
  { number: 106, name: 'قريش', ayahs: 4, page: 602 },
  { number: 107, name: 'الماعون', ayahs: 7, page: 602 },
  { number: 108, name: 'الكوثر', ayahs: 3, page: 602 },
  { number: 109, name: 'الكافرون', ayahs: 6, page: 603 },
  { number: 110, name: 'النصر', ayahs: 3, page: 603 },
  { number: 111, name: 'المسد', ayahs: 5, page: 603 },
  { number: 112, name: 'الإخلاص', ayahs: 4, page: 604 },
  { number: 113, name: 'الفلق', ayahs: 5, page: 604 },
  { number: 114, name: 'الناس', ayahs: 6, page: 604 }
];