// تكوين التطبيق الرئيسي
export const APP_CONFIG = {
  version: '1.4.0',
  name: 'تطبيق القرآن الكريم التعليمي',
  developer: 'عبدالرحمن عوض صالح الرشيدي للبرمجة وتطوير',
  // API URLs
  quranAPI: 'https://api.alquran.cloud/v1/',
  quranTranslationAPI: 'https://api.alquran.cloud/v1/quran/',
  tafsirAPI: 'https://api.quran.com/api/v4/',
  prayerAPI: 'https://api.aladhan.com/v1/',
  hadithAPI: 'https://api.hadith.gading.dev/books/',
  audioBaseURL: 'https://cdn.islamic.network/quran/audio/128/',
  copyright: {
    year: new Date().getFullYear(),
    owner: "عبدالرحمن عوض صالح الرشيدي للبرمجة وتطوير",
    phone: "+966 599900121",
    email: "Tiger3Saudi@gmail.com",
    location: "المملكة العربية السعودية، الرياض",
    rights: "جميع الحقوق محفوظة"
  }
};

// قائمة القراء مع روابط الصوت
export const RECITERS = [
  { id: 'ar.alafasy', name: 'مشاري راشد العفاسي', language: 'ar' },
  { id: 'ar.abdulbasitmurattal', name: 'عبد الباسط عبد الصمد', language: 'ar' },
  { id: 'ar.abdurrahmaansudais', name: 'عبد الرحمن السديس', language: 'ar' },
  { id: 'ar.hanirifai', name: 'هاني الرفاعي', language: 'ar' },
  { id: 'ar.husary', name: 'محمود خليل الحصري', language: 'ar' },
  { id: 'ar.mahermuaiqly', name: 'ماهر المعيقلي', language: 'ar' },
  { id: 'ar.minshawi', name: 'محمد صديق المنشاوي', language: 'ar' },
  { id: 'ar.muhammadayyoub', name: 'محمد أيوب', language: 'ar' },
];

// بيانات اللغات والترجمات المتاحة
export const LANGUAGES = [
  { code: 'ar', name: 'العربية', direction: 'rtl', translation: 'ar.asad' },
  { code: 'en', name: 'English', direction: 'ltr', translation: 'en.sahih' },
  { code: 'fr', name: 'Français', direction: 'ltr', translation: 'fr.hamidullah' },
  { code: 'ur', name: 'اردو', direction: 'rtl', translation: 'ur.jalandhry' },
  { code: 'id', name: 'Bahasa Indonesia', direction: 'ltr', translation: 'id.indonesian' },
];

// بيانات كتب الحديث المتوفرة
export const HADITH_BOOKS = [
  { id: 'bukhari', name: 'صحيح البخاري', chapterCount: 98, totalHadith: 7563 },
  { id: 'muslim', name: 'صحيح مسلم', chapterCount: 57, totalHadith: 7563 },
  { id: 'tirmidzi', name: 'جامع الترمذي', chapterCount: 49, totalHadith: 3956 },
  { id: 'abudawud', name: 'سنن أبي داود', chapterCount: 43, totalHadith: 5274 },
  { id: 'nasai', name: 'سنن النسائي', chapterCount: 52, totalHadith: 5761 },
  { id: 'ibnmajah', name: 'سنن ابن ماجه', chapterCount: 37, totalHadith: 4341 },
  { id: 'malik', name: 'موطأ مالك', chapterCount: 61, totalHadith: 1849 },
  { id: 'ahmad', name: 'مسند أحمد', chapterCount: 40, totalHadith: 26363 },
];

// بيانات التفاسير المتوفرة
export const TAFSIR_SOURCES = [
  { id: 'ar-tafsir-al-jalalayn', name: 'تفسير الجلالين', language: 'ar' },
  { id: 'ar-tafsir-ibn-kathir', name: 'تفسير ابن كثير', language: 'ar' },
  { id: 'ar-tafsir-al-qurtubi', name: 'تفسير القرطبي', language: 'ar' },
  { id: 'ar-tafsir-al-tabari', name: 'تفسير الطبري', language: 'ar' },
  { id: 'en-tafsir-ibn-kathir', name: 'Tafsir Ibn Kathir', language: 'en' },
];

// أسماء السور وأرقام صفحاتها
export const SURAH_NAMES = [
  { number: 1, name: "الفاتحة", englishName: "Al-Faatiha", page: 1 },
  { number: 2, name: "البقرة", englishName: "Al-Baqara", page: 2 },
  { number: 3, name: "آل عمران", englishName: "Aal-Imraan", page: 50 },
  { number: 4, name: "النساء", englishName: "An-Nisaa", page: 77 },
  { number: 5, name: "المائدة", englishName: "Al-Maaida", page: 106 },
  { number: 6, name: "الأنعام", englishName: "Al-An'aam", page: 128 },
  { number: 7, name: "الأعراف", englishName: "Al-A'raaf", page: 151 },
  { number: 8, name: "الأنفال", englishName: "Al-Anfaal", page: 177 },
  { number: 9, name: "التوبة", englishName: "At-Tawba", page: 187 },
  { number: 10, name: "يونس", englishName: "Yunus", page: 208 },
  { number: 11, name: "هود", englishName: "Hud", page: 221 },
  { number: 12, name: "يوسف", englishName: "Yusuf", page: 235 },
  { number: 13, name: "الرعد", englishName: "Ar-Ra'd", page: 249 },
  { number: 14, name: "إبراهيم", englishName: "Ibrahim", page: 255 },
  { number: 15, name: "الحجر", englishName: "Al-Hijr", page: 262 },
  { number: 16, name: "النحل", englishName: "An-Nahl", page: 267 },
  { number: 17, name: "الإسراء", englishName: "Al-Israa", page: 282 },
  { number: 18, name: "الكهف", englishName: "Al-Kahf", page: 293 },
  { number: 19, name: "مريم", englishName: "Maryam", page: 305 },
  { number: 20, name: "طه", englishName: "Taa-Haa", page: 312 },
  { number: 21, name: "الأنبياء", englishName: "Al-Anbiyaa" },
  { number: 22, name: "الحج", englishName: "Al-Hajj" },
  { number: 23, name: "المؤمنون", englishName: "Al-Muminoon" },
  { number: 24, name: "النور", englishName: "An-Noor" },
  { number: 25, name: "الفرقان", englishName: "Al-Furqaan" },
  { number: 26, name: "الشعراء", englishName: "Ash-Shu'araa" },
  { number: 27, name: "النمل", englishName: "An-Naml" },
  { number: 28, name: "القصص", englishName: "Al-Qasas" },
  { number: 29, name: "العنكبوت", englishName: "Al-Ankaboot" },
  { number: 30, name: "الروم", englishName: "Ar-Room" },
  { number: 31, name: "لقمان", englishName: "Luqman" },
  { number: 32, name: "السجدة", englishName: "As-Sajda" },
  { number: 33, name: "الأحزاب", englishName: "Al-Ahzaab" },
  { number: 34, name: "سبأ", englishName: "Saba" },
  { number: 35, name: "فاطر", englishName: "Faatir" },
  { number: 36, name: "يس", englishName: "Yaseen" },
  { number: 37, name: "الصافات", englishName: "As-Saaffaat" },
  { number: 38, name: "ص", englishName: "Saad" },
  { number: 39, name: "الزمر", englishName: "Az-Zumar" },
  { number: 40, name: "غافر", englishName: "Ghafir" },
  { number: 41, name: "فصلت", englishName: "Fussilat" },
  { number: 42, name: "الشورى", englishName: "Ash-Shura" },
  { number: 43, name: "الزخرف", englishName: "Az-Zukhruf" },
  { number: 44, name: "الدخان", englishName: "Ad-Dukhaan" },
  { number: 45, name: "الجاثية", englishName: "Al-Jaathiya" },
  { number: 46, name: "الأحقاف", englishName: "Al-Ahqaf" },
  { number: 47, name: "محمد", englishName: "Muhammad" },
  { number: 48, name: "الفتح", englishName: "Al-Fath" },
  { number: 49, name: "الحجرات", englishName: "Al-Hujuraat" },
  { number: 50, name: "ق", englishName: "Qaaf" },
  { number: 51, name: "الذاريات", englishName: "Adh-Dhaariyat" },
  { number: 52, name: "الطور", englishName: "At-Tur" },
  { number: 53, name: "النجم", englishName: "An-Najm" },
  { number: 54, name: "القمر", englishName: "Al-Qamar" },
  { number: 55, name: "الرحمن", englishName: "Ar-Rahmaan" },
  { number: 56, name: "الواقعة", englishName: "Al-Waaqia" },
  { number: 57, name: "الحديد", englishName: "Al-Hadid" },
  { number: 58, name: "المجادلة", englishName: "Al-Mujaadila" },
  { number: 59, name: "الحشر", englishName: "Al-Hashr" },
  { number: 60, name: "الممتحنة", englishName: "Al-Mumtahana" },
  { number: 61, name: "الصف", englishName: "As-Saff" },
  { number: 62, name: "الجمعة", englishName: "Al-Jumu'a" },
  { number: 63, name: "المنافقون", englishName: "Al-Munaafiqoon" },
  { number: 64, name: "التغابن", englishName: "At-Taghaabun" },
  { number: 65, name: "الطلاق", englishName: "At-Talaaq" },
  { number: 66, name: "التحريم", englishName: "At-Tahrim" },
  { number: 67, name: "الملك", englishName: "Al-Mulk" },
  { number: 68, name: "القلم", englishName: "Al-Qalam" },
  { number: 69, name: "الحاقة", englishName: "Al-Haaqqa" },
  { number: 70, name: "المعارج", englishName: "Al-Ma'aarij" },
  { number: 71, name: "نوح", englishName: "Nooh" },
  { number: 72, name: "الجن", englishName: "Al-Jinn" },
  { number: 73, name: "المزمل", englishName: "Al-Muzzammil" },
  { number: 74, name: "المدثر", englishName: "Al-Muddaththir" },
  { number: 75, name: "القيامة", englishName: "Al-Qiyaama" },
  { number: 76, name: "الإنسان", englishName: "Al-Insaan" },
  { number: 77, name: "المرسلات", englishName: "Al-Mursalaat" },
  { number: 78, name: "النبأ", englishName: "An-Naba" },
  { number: 79, name: "النازعات", englishName: "An-Naazi'aat" },
  { number: 80, name: "عبس", englishName: "Abasa" },
  { number: 81, name: "التكوير", englishName: "At-Takwir" },
  { number: 82, name: "الإنفطار", englishName: "Al-Infitaar" },
  { number: 83, name: "المطففين", englishName: "Al-Mutaffifin" },
  { number: 84, name: "الإنشقاق", englishName: "Al-Inshiqaaq" },
  { number: 85, name: "البروج", englishName: "Al-Burooj" },
  { number: 86, name: "الطارق", englishName: "At-Taariq" },
  { number: 87, name: "الأعلى", englishName: "Al-A'laa" },
  { number: 88, name: "الغاشية", englishName: "Al-Ghaashiya" },
  { number: 89, name: "الفجر", englishName: "Al-Fajr" },
  { number: 90, name: "البلد", englishName: "Al-Balad" },
  { number: 91, name: "الشمس", englishName: "Ash-Shams" },
  { number: 92, name: "الليل", englishName: "Al-Lail" },
  { number: 93, name: "الضحى", englishName: "Ad-Dhuhaa" },
  { number: 94, name: "الشرح", englishName: "Ash-Sharh" },
  { number: 95, name: "التين", englishName: "At-Tin" },
  { number: 96, name: "العلق", englishName: "Al-Alaq" },
  { number: 97, name: "القدر", englishName: "Al-Qadr" },
  { number: 98, name: "البينة", englishName: "Al-Bayyina" },
  { number: 99, name: "الزلزلة", englishName: "Az-Zalzala" },
  { number: 100, name: "العاديات", englishName: "Al-Aadiyaat" },
  { number: 101, name: "القارعة", englishName: "Al-Qaari'a" },
  { number: 102, name: "التكاثر", englishName: "At-Takaathur" },
  { number: 103, name: "العصر", englishName: "Al-Asr" },
  { number: 104, name: "الهمزة", englishName: "Al-Humaza" },
  { number: 105, name: "الفيل", englishName: "Al-Fil" },
  { number: 106, name: "قريش", englishName: "Quraish" },
  { number: 107, name: "الماعون", englishName: "Al-Maa'un" },
  { number: 108, name: "الكوثر", englishName: "Al-Kawthar" },
  { number: 109, name: "الكافرون", englishName: "Al-Kaafiroon" },
  { number: 110, name: "النصر", englishName: "An-Nasr" },
  { number: 111, name: "المسد", englishName: "Al-Masad" },
  { number: 112, name: "الإخلاص", englishName: "Al-Ikhlaas" },
  { number: 113, name: "الفلق", englishName: "Al-Falaq" },
  { number: 114, name: "الناس", englishName: "An-Naas" }
];
