// ثوابت التطبيق

// إجمالي عدد صفحات المصحف
export const TOTAL_PAGES = 604;

export const APP_CONFIG = {
  NAME: 'القرآن الكريم',
  VERSION: '1.0.0',
  DEFAULT_PAGE: 1,
  TOTAL_PAGES: 604, // العدد الكامل لصفحات المصحف
  DEFAULT_SURAH: 1,
  TOTAL_SURAHS: 114,
  DEFAULT_JUZ: 1,
  TOTAL_JUZS: 30,
  DEFAULT_LANGUAGE: 'ar',
  DEFAULT_RECITER: 'mishary_rashid_alafasy',
  DEFAULT_TRANSLATION: 'ar.muyassar',
  DEFAULT_TAFSIR: 'ar.muyassar',
  DEFAULT_THEME: 'light',
  API_BASE_URL: ''
};

// قائمة القراء
export const RECITERS = [
  { id: 'mishary_rashid_alafasy', name: 'مشاري راشد العفاسي' },
  { id: 'abdurrahmaan_as_sudais', name: 'عبد الرحمن السديس' },
  { id: 'abu_bakr_ash_shaatree', name: 'أبو بكر الشاطري' },
  { id: 'hani_rifai', name: 'هاني الرفاعي' },
  { id: 'mahmoud_khalil_al_husary', name: 'محمود خليل الحصري' },
  { id: 'muhammad_siddiq_al_minshawi', name: 'محمد صديق المنشاوي' },
  { id: 'abdullah_basfar', name: 'عبد الله بصفر' },
  { id: 'abdul_basit_abdul_samad', name: 'عبد الباسط عبد الصمد' },
  { id: 'saud_al_shuraim', name: 'سعود الشريم' },
  { id: 'maher_al_muaiqly', name: 'ماهر المعيقلي' },
];

// قائمة اللغات المدعومة للترجمة
export const LANGUAGES = [
  { id: 'ar', name: 'العربية', english_name: 'Arabic' },
  { id: 'en', name: 'الإنجليزية', english_name: 'English' },
  { id: 'fr', name: 'الفرنسية', english_name: 'French' },
  { id: 'tr', name: 'التركية', english_name: 'Turkish' },
  { id: 'ur', name: 'الأردية', english_name: 'Urdu' },
  { id: 'id', name: 'الإندونيسية', english_name: 'Indonesian' },
  { id: 'ru', name: 'الروسية', english_name: 'Russian' },
  { id: 'es', name: 'الإسبانية', english_name: 'Spanish' },
  { id: 'bn', name: 'البنغالية', english_name: 'Bengali' },
  { id: 'zh', name: 'الصينية', english_name: 'Chinese' },
];

// قائمة كتب الحديث
export const HADITH_BOOKS = [
  { id: 'bukhari', name: 'صحيح البخاري' },
  { id: 'muslim', name: 'صحيح مسلم' },
  { id: 'tirmidhi', name: 'سنن الترمذي' },
  { id: 'abudawud', name: 'سنن أبي داود' },
  { id: 'nasai', name: 'سنن النسائي' },
  { id: 'ibnmajah', name: 'سنن ابن ماجه' },
  { id: 'malik', name: 'موطأ مالك' },
  { id: 'riyadussalihin', name: 'رياض الصالحين' },
  { id: 'adab', name: 'الأدب المفرد' },
  { id: 'bulugh', name: 'بلوغ المرام' },
];

// قائمة مصادر التفسير
export const TAFSIR_SOURCES = [
  { id: 'ar.muyassar', name: 'التفسير الميسر' },
  { id: 'ar.jalalayn', name: 'تفسير الجلالين' },
  { id: 'ar.baghawy', name: 'تفسير البغوي' },
  { id: 'ar.ibnkathir', name: 'تفسير ابن كثير' },
  { id: 'ar.qurtubi', name: 'تفسير القرطبي' },
  { id: 'ar.tabari', name: 'تفسير الطبري' },
  { id: 'ar.waseet', name: 'التفسير الوسيط' },
  { id: 'ar.sa3dy', name: 'تفسير السعدي' },
  { id: 'en.tafisr-ibn-kathir', name: 'تفسير ابن كثير (إنجليزي)' },
  { id: 'en.ahmedali', name: 'ترجمة أحمد علي' },
];

// قائمة أسماء السور
export const SURAH_NAMES = [
  { number: 1, name: 'الفاتحة', transliteration: 'Al-Fatihah', translation: 'The Opening', totalVerses: 7 },
  { number: 2, name: 'البقرة', transliteration: 'Al-Baqarah', translation: 'The Cow', totalVerses: 286 },
  { number: 3, name: 'آل عمران', transliteration: 'Aal-Imran', translation: 'Family of Imran', totalVerses: 200 },
  { number: 4, name: 'النساء', transliteration: 'An-Nisa', translation: 'The Women', totalVerses: 176 },
  { number: 5, name: 'المائدة', transliteration: 'Al-Ma\'idah', translation: 'The Table Spread', totalVerses: 120 },
  { number: 6, name: 'الأنعام', transliteration: 'Al-An\'am', translation: 'The Cattle', totalVerses: 165 },
  { number: 7, name: 'الأعراف', transliteration: 'Al-A\'raf', translation: 'The Heights', totalVerses: 206 },
  { number: 8, name: 'الأنفال', transliteration: 'Al-Anfal', translation: 'The Spoils of War', totalVerses: 75 },
  { number: 9, name: 'التوبة', transliteration: 'At-Tawbah', translation: 'The Repentance', totalVerses: 129 },
  { number: 10, name: 'يونس', transliteration: 'Yunus', translation: 'Jonah', totalVerses: 109 },
  { number: 11, name: 'هود', transliteration: 'Hud', translation: 'Hud', totalVerses: 123 },
  { number: 12, name: 'يوسف', transliteration: 'Yusuf', translation: 'Joseph', totalVerses: 111 },
  { number: 13, name: 'الرعد', transliteration: 'Ar-Ra\'d', translation: 'The Thunder', totalVerses: 43 },
  { number: 14, name: 'إبراهيم', transliteration: 'Ibrahim', translation: 'Abraham', totalVerses: 52 },
  { number: 15, name: 'الحجر', transliteration: 'Al-Hijr', translation: 'The Rocky Tract', totalVerses: 99 },
  { number: 16, name: 'النحل', transliteration: 'An-Nahl', translation: 'The Bee', totalVerses: 128 },
  { number: 17, name: 'الإسراء', transliteration: 'Al-Isra', translation: 'The Night Journey', totalVerses: 111 },
  { number: 18, name: 'الكهف', transliteration: 'Al-Kahf', translation: 'The Cave', totalVerses: 110 },
  { number: 19, name: 'مريم', transliteration: 'Maryam', translation: 'Mary', totalVerses: 98 },
  { number: 20, name: 'طه', transliteration: 'Ta-Ha', translation: 'Ta-Ha', totalVerses: 135 },
  { number: 21, name: 'الأنبياء', transliteration: 'Al-Anbiya', translation: 'The Prophets', totalVerses: 112 },
  { number: 22, name: 'الحج', transliteration: 'Al-Hajj', translation: 'The Pilgrimage', totalVerses: 78 },
  { number: 23, name: 'المؤمنون', transliteration: 'Al-Mu\'minun', translation: 'The Believers', totalVerses: 118 },
  { number: 24, name: 'النور', transliteration: 'An-Nur', translation: 'The Light', totalVerses: 64 },
  { number: 25, name: 'الفرقان', transliteration: 'Al-Furqan', translation: 'The Criterion', totalVerses: 77 },
  { number: 26, name: 'الشعراء', transliteration: 'Ash-Shu\'ara', translation: 'The Poets', totalVerses: 227 },
  { number: 27, name: 'النمل', transliteration: 'An-Naml', translation: 'The Ant', totalVerses: 93 },
  { number: 28, name: 'القصص', transliteration: 'Al-Qasas', translation: 'The Stories', totalVerses: 88 },
  { number: 29, name: 'العنكبوت', transliteration: 'Al-Ankabut', translation: 'The Spider', totalVerses: 69 },
  { number: 30, name: 'الروم', transliteration: 'Ar-Rum', translation: 'The Romans', totalVerses: 60 },
  { number: 31, name: 'لقمان', transliteration: 'Luqman', translation: 'Luqman', totalVerses: 34 },
  { number: 32, name: 'السجدة', transliteration: 'As-Sajdah', translation: 'The Prostration', totalVerses: 30 },
  { number: 33, name: 'الأحزاب', transliteration: 'Al-Ahzab', translation: 'The Combined Forces', totalVerses: 73 },
  { number: 34, name: 'سبإ', transliteration: 'Saba', translation: 'Sheba', totalVerses: 54 },
  { number: 35, name: 'فاطر', transliteration: 'Fatir', translation: 'Originator', totalVerses: 45 },
  { number: 36, name: 'يس', transliteration: 'Ya-Sin', translation: 'Ya Sin', totalVerses: 83 },
  { number: 37, name: 'الصافات', transliteration: 'As-Saffat', translation: 'Those who set the Ranks', totalVerses: 182 },
  { number: 38, name: 'ص', transliteration: 'Sad', translation: 'The Letter Sad', totalVerses: 88 },
  { number: 39, name: 'الزمر', transliteration: 'Az-Zumar', translation: 'The Troops', totalVerses: 75 },
  { number: 40, name: 'غافر', transliteration: 'Ghafir', translation: 'The Forgiver', totalVerses: 85 },
  { number: 41, name: 'فصلت', transliteration: 'Fussilat', translation: 'Explained in Detail', totalVerses: 54 },
  { number: 42, name: 'الشورى', transliteration: 'Ash-Shura', translation: 'The Consultation', totalVerses: 53 },
  { number: 43, name: 'الزخرف', transliteration: 'Az-Zukhruf', translation: 'The Ornaments of Gold', totalVerses: 89 },
  { number: 44, name: 'الدخان', transliteration: 'Ad-Dukhan', translation: 'The Smoke', totalVerses: 59 },
  { number: 45, name: 'الجاثية', transliteration: 'Al-Jathiyah', translation: 'The Crouching', totalVerses: 37 },
  { number: 46, name: 'الأحقاف', transliteration: 'Al-Ahqaf', translation: 'The Wind-Curved Sandhills', totalVerses: 35 },
  { number: 47, name: 'محمد', transliteration: 'Muhammad', translation: 'Muhammad', totalVerses: 38 },
  { number: 48, name: 'الفتح', transliteration: 'Al-Fath', translation: 'The Victory', totalVerses: 29 },
  { number: 49, name: 'الحجرات', transliteration: 'Al-Hujurat', translation: 'The Rooms', totalVerses: 18 },
  { number: 50, name: 'ق', transliteration: 'Qaf', translation: 'The Letter Qaf', totalVerses: 45 },
  { number: 51, name: 'الذاريات', transliteration: 'Adh-Dhariyat', translation: 'The Winnowing Winds', totalVerses: 60 },
  { number: 52, name: 'الطور', transliteration: 'At-Tur', translation: 'The Mount', totalVerses: 49 },
  { number: 53, name: 'النجم', transliteration: 'An-Najm', translation: 'The Star', totalVerses: 62 },
  { number: 54, name: 'القمر', transliteration: 'Al-Qamar', translation: 'The Moon', totalVerses: 55 },
  { number: 55, name: 'الرحمن', transliteration: 'Ar-Rahman', translation: 'The Beneficent', totalVerses: 78 },
  { number: 56, name: 'الواقعة', transliteration: 'Al-Waqi\'ah', translation: 'The Inevitable', totalVerses: 96 },
  { number: 57, name: 'الحديد', transliteration: 'Al-Hadid', translation: 'The Iron', totalVerses: 29 },
  { number: 58, name: 'المجادلة', transliteration: 'Al-Mujadila', translation: 'The Pleading Woman', totalVerses: 22 },
  { number: 59, name: 'الحشر', transliteration: 'Al-Hashr', translation: 'The Exile', totalVerses: 24 },
  { number: 60, name: 'الممتحنة', transliteration: 'Al-Mumtahanah', translation: 'She that is to be examined', totalVerses: 13 },
  { number: 61, name: 'الصف', transliteration: 'As-Saff', translation: 'The Ranks', totalVerses: 14 },
  { number: 62, name: 'الجمعة', transliteration: 'Al-Jumu\'ah', translation: 'The Congregation, Friday', totalVerses: 11 },
  { number: 63, name: 'المنافقون', transliteration: 'Al-Munafiqun', translation: 'The Hypocrites', totalVerses: 11 },
  { number: 64, name: 'التغابن', transliteration: 'At-Taghabun', translation: 'The Mutual Disillusion', totalVerses: 18 },
  { number: 65, name: 'الطلاق', transliteration: 'At-Talaq', translation: 'The Divorce', totalVerses: 12 },
  { number: 66, name: 'التحريم', transliteration: 'At-Tahrim', translation: 'The Prohibition', totalVerses: 12 },
  { number: 67, name: 'الملك', transliteration: 'Al-Mulk', translation: 'The Sovereignty', totalVerses: 30 },
  { number: 68, name: 'القلم', transliteration: 'Al-Qalam', translation: 'The Pen', totalVerses: 52 },
  { number: 69, name: 'الحاقة', transliteration: 'Al-Haqqah', translation: 'The Reality', totalVerses: 52 },
  { number: 70, name: 'المعارج', transliteration: 'Al-Ma\'arij', translation: 'The Ascending Stairways', totalVerses: 44 },
  { number: 71, name: 'نوح', transliteration: 'Nuh', translation: 'Noah', totalVerses: 28 },
  { number: 72, name: 'الجن', transliteration: 'Al-Jinn', translation: 'The Jinn', totalVerses: 28 },
  { number: 73, name: 'المزمل', transliteration: 'Al-Muzzammil', translation: 'The Enshrouded One', totalVerses: 20 },
  { number: 74, name: 'المدثر', transliteration: 'Al-Muddathir', translation: 'The Cloaked One', totalVerses: 56 },
  { number: 75, name: 'القيامة', transliteration: 'Al-Qiyamah', translation: 'The Resurrection', totalVerses: 40 },
  { number: 76, name: 'الانسان', transliteration: 'Al-Insan', translation: 'The Man', totalVerses: 31 },
  { number: 77, name: 'المرسلات', transliteration: 'Al-Mursalat', translation: 'The Emissaries', totalVerses: 50 },
  { number: 78, name: 'النبإ', transliteration: 'An-Naba', translation: 'The Tidings', totalVerses: 40 },
  { number: 79, name: 'النازعات', transliteration: 'An-Nazi\'at', translation: 'Those who drag forth', totalVerses: 46 },
  { number: 80, name: 'عبس', transliteration: 'Abasa', translation: 'He Frowned', totalVerses: 42 },
  { number: 81, name: 'التكوير', transliteration: 'At-Takwir', translation: 'The Overthrowing', totalVerses: 29 },
  { number: 82, name: 'الإنفطار', transliteration: 'Al-Infitar', translation: 'The Cleaving', totalVerses: 19 },
  { number: 83, name: 'المطففين', transliteration: 'Al-Mutaffifin', translation: 'The Defrauding', totalVerses: 36 },
  { number: 84, name: 'الإنشقاق', transliteration: 'Al-Inshiqaq', translation: 'The Sundering', totalVerses: 25 },
  { number: 85, name: 'البروج', transliteration: 'Al-Buruj', translation: 'The Mansions of the Stars', totalVerses: 22 },
  { number: 86, name: 'الطارق', transliteration: 'At-Tariq', translation: 'The Morning Star', totalVerses: 17 },
  { number: 87, name: 'الأعلى', transliteration: 'Al-A\'la', translation: 'The Most High', totalVerses: 19 },
  { number: 88, name: 'الغاشية', transliteration: 'Al-Ghashiyah', translation: 'The Overwhelming', totalVerses: 26 },
  { number: 89, name: 'الفجر', transliteration: 'Al-Fajr', translation: 'The Dawn', totalVerses: 30 },
  { number: 90, name: 'البلد', transliteration: 'Al-Balad', translation: 'The City', totalVerses: 20 },
  { number: 91, name: 'الشمس', transliteration: 'Ash-Shams', translation: 'The Sun', totalVerses: 15 },
  { number: 92, name: 'الليل', transliteration: 'Al-Layl', translation: 'The Night', totalVerses: 21 },
  { number: 93, name: 'الضحى', transliteration: 'Ad-Duhaa', translation: 'The Morning Hours', totalVerses: 11 },
  { number: 94, name: 'الشرح', transliteration: 'Ash-Sharh', translation: 'The Relief', totalVerses: 8 },
  { number: 95, name: 'التين', transliteration: 'At-Tin', translation: 'The Fig', totalVerses: 8 },
  { number: 96, name: 'العلق', transliteration: 'Al-Alaq', translation: 'The Clot', totalVerses: 19 },
  { number: 97, name: 'القدر', transliteration: 'Al-Qadr', translation: 'The Power', totalVerses: 5 },
  { number: 98, name: 'البينة', transliteration: 'Al-Bayyinah', translation: 'The Clear Proof', totalVerses: 8 },
  { number: 99, name: 'الزلزلة', transliteration: 'Az-Zalzalah', translation: 'The Earthquake', totalVerses: 8 },
  { number: 100, name: 'العاديات', transliteration: 'Al-Adiyat', translation: 'The Courser', totalVerses: 11 },
  { number: 101, name: 'القارعة', transliteration: 'Al-Qariah', translation: 'The Calamity', totalVerses: 11 },
  { number: 102, name: 'التكاثر', transliteration: 'At-Takathur', translation: 'The Rivalry in world increase', totalVerses: 8 },
  { number: 103, name: 'العصر', transliteration: 'Al-Asr', translation: 'The Declining Day', totalVerses: 3 },
  { number: 104, name: 'الهمزة', transliteration: 'Al-Humazah', translation: 'The Traducer', totalVerses: 9 },
  { number: 105, name: 'الفيل', transliteration: 'Al-Fil', translation: 'The Elephant', totalVerses: 5 },
  { number: 106, name: 'قريش', transliteration: 'Quraysh', translation: 'Quraysh', totalVerses: 4 },
  { number: 107, name: 'الماعون', transliteration: 'Al-Ma\'un', translation: 'The Small Kindnesses', totalVerses: 7 },
  { number: 108, name: 'الكوثر', transliteration: 'Al-Kawthar', translation: 'The Abundance', totalVerses: 3 },
  { number: 109, name: 'الكافرون', transliteration: 'Al-Kafirun', translation: 'The Disbelievers', totalVerses: 6 },
  { number: 110, name: 'النصر', transliteration: 'An-Nasr', translation: 'The Divine Support', totalVerses: 3 },
  { number: 111, name: 'المسد', transliteration: 'Al-Masad', translation: 'The Palm Fiber', totalVerses: 5 },
  { number: 112, name: 'الإخلاص', transliteration: 'Al-Ikhlas', translation: 'The Sincerity', totalVerses: 4 },
  { number: 113, name: 'الفلق', transliteration: 'Al-Falaq', translation: 'The Daybreak', totalVerses: 5 },
  { number: 114, name: 'الناس', transliteration: 'An-Nas', translation: 'The Mankind', totalVerses: 6 }
];